on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@5c625bfb5d1ff62eadeeb3772007f7f66fdcf071 # v4
        id: release
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        if: ${{ steps.release.outputs.releases_created }}

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: lts/*
          registry-url: "https://registry.npmjs.org"
          cache: npm
          cache-dependency-path: package-lock.json
        if: ${{ steps.release.outputs.releases_created }}

      - run: npm ci
        if: ${{ steps.release.outputs.releases_created }}

      - run: npm run build --workspaces --if-present
        if: ${{ steps.release.outputs.releases_created }}

      - run: npm publish --workspace packages/asc-sdk --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: ${{ steps.release.outputs['packages/asc-sdk--release_created'] }}

      - run: npm publish --workspace packages/asc-auth --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: ${{ steps.release.outputs['packages/asc-auth--release_created'] }}
